// Product catalog
export const placeholderProducts = [

  // ── FARMACIA ──────────────────────────────────────
  {
    id: 1,
    name_es: 'Tylenol Extra Fuerte',
    name_en: 'Tylenol Extra Strength',
    price: 9.99,
    category: 'farmacia',
    image: '/products/tylenol.webp',
  },
  {
    id: 2,
    name_es: 'Advil Ibuprofeno 200mg',
    name_en: 'Advil Ibuprofen 200mg',
    price: 8.49,
    category: 'farmacia',
    image: '/products/advil.webp',
  },
  {
    id: 3,
    name_es: 'Vick VapoRub',
    name_en: 'Vicks VapoRub',
    price: 6.99,
    category: 'farmacia',
    image: '/products/vaporub.jpg',
  },
  {
    id: 4,
    name_es: 'Curitas Band-Aid',
    name_en: 'Band-Aid Bandages',
    price: 4.49,
    category: 'farmacia',
    image: '/products/bandaid.png',
  },
  {
    id: 5,
    name_es: 'Pepto-Bismol Líquido',
    name_en: 'Pepto-Bismol Liquid',
    price: 7.49,
    category: 'farmacia',
    image: '/products/pepto.webp',
  },
  {
    id: 15,
    name_es: 'Vaselina Original',
    name_en: 'Vaseline Healing Jelly',
    price: 4.99,
    category: 'farmacia',
    image: '/products/vaseline.jpg',
  },
  {
    id: 16,
    name_es: 'Vitaminas Alive! Mujer',
    name_en: 'Alive! Women\'s Multivitamin',
    price: 12.99,
    category: 'farmacia',
    image: '/products/vitaminas.jpg',
  },

  // ── COMIDA ────────────────────────────────────────
  {
    id: 6,
    name_es: 'Café Bustelo Espresso',
    name_en: 'Café Bustelo Espresso',
    price: 5.99,
    category: 'comida',
    image: '/products/bustelo.jpg',
  },
  {
    id: 7,
    name_es: 'Galletas María Gamesa',
    name_en: 'Gamesa María Cookies',
    price: 3.49,
    category: 'comida',
    image: '/products/galletas.jpg',
  },
  {
    id: 8,
    name_es: 'Arroz Grano Largo',
    name_en: 'Long Grain White Rice',
    price: 6.99,
    category: 'comida',
    image: '/products/arroz.jpg',
  },
  {
    id: 9,
    name_es: 'Chocolate Abuelita',
    name_en: 'Abuelita Hot Chocolate',
    price: 4.99,
    category: 'comida',
    image: '/products/chocolate.jpg',
  },
  {
    id: 17,
    name_es: 'Tang Naranja en Polvo',
    name_en: 'Tang Orange Drink Mix',
    price: 2.49,
    category: 'comida',
    image: '/products/tang.webp',
  },
  {
    id: 18,
    name_es: 'Nestlé Milo Bebida',
    name_en: 'Nestlé Milo Drink',
    price: 7.99,
    category: 'comida',
    image: '/products/milo.jpg',
  },
  {
    id: 19,
    name_es: 'Takis Fuego',
    name_en: 'Takis Fuego Chips',
    price: 3.99,
    category: 'comida',
    image: '/products/takis.jpg',
  },
  {
    id: 20,
    name_es: 'Doritos Nacho Cheese',
    name_en: 'Doritos Nacho Cheese',
    price: 3.99,
    category: 'comida',
    image: '/products/doritos.jpg',
  },
  {
    id: 21,
    name_es: 'Cheetos Crujientes',
    name_en: 'Cheetos Crunchy',
    price: 3.49,
    category: 'comida',
    image: '/products/cheetos.jpg',
  },

  // ── LIMPIEZA ──────────────────────────────────────
  {
    id: 10,
    name_es: 'Fabuloso Lavanda',
    name_en: 'Fabuloso Lavender Cleaner',
    price: 3.99,
    category: 'limpieza',
    image: '/products/fabuloso.webp',
  },
  {
    id: 11,
    name_es: 'Cloro Clorox Regular',
    name_en: 'Clorox Bleach Regular',
    price: 4.49,
    category: 'limpieza',
    image: '/products/clorox.jpg',
  },
  {
    id: 12,
    name_es: 'Detergente Tide Original',
    name_en: 'Tide Laundry Detergent',
    price: 12.99,
    category: 'limpieza',
    image: '/products/tide.jpg',
  },
  {
    id: 13,
    name_es: 'Jabón de Platos Dawn',
    name_en: 'Dawn Dish Soap',
    price: 3.49,
    category: 'limpieza',
    image: '/products/dawn.webp',
  },
  {
    id: 22,
    name_es: 'Detergente Gain Spring',
    name_en: 'Gain Spring Daydream Detergent',
    price: 11.99,
    category: 'limpieza',
    image: '/products/gain.jpg',
  },
  {
    id: 23,
    name_es: 'Shampoo Pantene 3 en 1',
    name_en: 'Pantene 3-in-1 Shampoo',
    price: 7.99,
    category: 'limpieza',
    image: '/products/pantene.jpg',
  },
  {
    id: 24,
    name_es: 'Dove Crema de Baño',
    name_en: 'Dove Deep Moisture Body Wash',
    price: 6.99,
    category: 'limpieza',
    image: '/products/dove.jpg',
  },
  {
    id: 25,
    name_es: 'Papel Higiénico Charmin',
    name_en: 'Charmin Ultra Soft Toilet Paper',
    price: 9.99,
    category: 'limpieza',
    image: '/products/charmin.jpg',
  },
  {
    id: 26,
    name_es: 'Suavizante Downy April Fresh',
    name_en: 'Downy April Fresh Fabric Softener',
    price: 8.99,
    category: 'limpieza',
    image: '/products/downy.avif',
  },

  // ── UTILIDADES ────────────────────────────────────
  {
    id: 14,
    name_es: 'Pilas AA Duracell (4 pack)',
    name_en: 'Duracell AA Batteries (4 pack)',
    price: 6.99,
    category: 'utilidades',
    image: '/products/pilas.jpg',
  },
  {
    id: 27,
    name_es: 'Vaporizador Eléctrico Brentwood',
    name_en: 'Brentwood Electric Food Steamer',
    price: 24.99,
    category: 'utilidades',
    image: '/products/steamer.webp',
  },
  {
    id: 28,
    name_es: 'Sartén Antiadherente',
    name_en: 'Non-Stick Frying Pan',
    price: 14.99,
    category: 'utilidades',
    image: '/products/sarten.webp',
  },
];
